### ISSUE TITLE
Cannot use Puzzle with symfony 4

### ISSUE THREAD

**Issue by matracine** [puzzle-org/configuration#5]
Hello,
dependency "symfony/yaml" : "~3.2", prevents use of puzzle/configuration with symfony 4.
Is it possible to update that ?

Cheers amigo.

**Comment by Niktux** [comment]
Hi @matracine,
Sorry didn't have issue notification :-(
Having the same pb here ... and discovering your issue
We will fix that promptly

Cheers ;-)

**Comment by Niktux** [comment]
Fixed in 4.0.2

**Comment by matracine** [comment]
> Hi @matracine,
> Sorry didn't have issue notification :-(
> Having the same pb here ... and discovering your issue
> We will fix that promptly
> 
> Cheers ;-)

Great :
Thanks :^)
